# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TwitterClone_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: TwitterClone_test

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TwitterClone_test
  pool: 5
  username: root
  password:
  host: localhost


production:
  <<: *default
  database: TwitterClone_production
  username: TwitterClone
  password: <%= ENV['TWITTERCLONE_DATABASE_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: TwitterClone_production
  pool: 5
  username: root
  password:
  host: localhost
